[CONFIGURATION] * NEW: Modify the installation process so that it will be able to run the   'gbh3' tool to extract help from component source files. Not usable yet   as long as 'gbh3' depends on 'gb.pcre'.
[HELP EXTRACTOR]
* NEW: Move 'gbh3' project from '/app/src' to '/main/tools'.
* NEW: Add new options that are needed by the installation process.


git-svn-id: svn://localhost/gambas/trunk@6829 867c0c6c-44f3-4631-809d-bfa615b0a4ec

diff --git a/main/Makefile.am b/main/Makefile.am
--- a/main/Makefile.am
+++ b/main/Makefile.am
@@ -1,6 +1,6 @@
 ACLOCAL_AMFLAGS = -I m4 --install
-SUBDIRS = gbc gbx lib share
-EXTRA_DIST = TODO reconf spec README mime gb.*.h
+SUBDIRS = gbc gbx . lib share
+EXTRA_DIST = TODO reconf tools spec README mime gb.*.h
 BUILT_SOURCES = trunk_version.h
 CLEANFILES = trunk_version.h
 
@@ -36,6 +36,29 @@ install-exec-local:
 		xdg-mime install $(srcdir)/mime/application-x-gambas3.xml; \
 	fi
 
+	@echo "Creating the information files for gb component..."
+	@$(INSTALL) -d $(DESTDIR)$(gbdatadir)/info
+	@$(DESTDIR)$(bindir)/gbi$(GAMBAS_VERSION) -r $(DESTDIR)$(prefix) gb
+	@rm -f $(DESTDIR)$(gblibdir)/lib.gb.la
+	@rm -f $(DESTDIR)$(gblibdir)/lib.gb.so*
+	@$(INSTALL) lib/gb.component $(DESTDIR)$(gblibdir)
+
+	@echo "Installing the compiler tools..."
+	@(cd $(srcdir)/tools; d=`pwd`; \
+	  for p in gb*; do \
+	    echo "Compiling $$p..."; cd $$d/$$p; \
+	    $(DESTDIR)$(bindir)/gbc$(GAMBAS_VERSION) -ag -r $(DESTDIR)$(prefix); \
+	    if test $$? -eq 0; then \
+	      $(DESTDIR)$(bindir)/gba$(GAMBAS_VERSION); \
+	      rm -rf .gambas; \
+	      echo "Installing $$p..."; \
+	      $(INSTALL) $$p.gambas $(DESTDIR)$(bindir); \
+	      ln -s $$p.gambas $(DESTDIR)$(bindir)/$$p || true; \
+	    else \
+	      echo "|| Unable to compile $$p" >> ../../../warnings.log; \
+	    fi \
+	  done)
+
 uninstall-local:
 	@rm -f $(DESTDIR)$(bindir)/gbr$(GAMBAS_VERSION)
 	@rm -rf $(DESTDIR)$(gblibdir)/info
@@ -43,6 +66,14 @@ uninstall-local:
 		xdg-mime uninstall $(srcdir)/mime/application-x-gambas3.xml; \
 		xdg-icon-resource uninstall --context mimetypes --size 64 application-x-gambas3; \
 	fi
+	@(cd $(srcdir)/tools; for p in gb*; do rm -f $(DESTDIR)$(bindir)/$$p.gambas $(DESTDIR)$(bindir)/$$p; done)
+	@rm -f $(DESTDIR)$(gblibdir)gb.component
+	@rm -rf $(DESTDIR)$(gbdatadir)/info/gb.info
+	@rm -rf $(DESTDIR)$(gbdatadir)/info/gb.list
 
 dist-hook:
 	@rm -f $(distdir)/trunk_version.h
+	@(cd $(distdir)/tools; \
+	rm -rf `find . -name ".gambas" -o -name ".action" -o -name ".lock" -o -name ".xvpics" -o -name "*~" -o -name "*.out"  -o -name "*.pot" -o -name "*.gambas" -o -name "core*" -o -name ".kdbg*" -o -name ".svn"`;)
+
+
