Update xdg-utils to 1.1.3 version.
[GB.DESKTOP]
* NEW: Update xdg-utils to 1.1.3 version.

diff --git a/comp/src/gb.desktop/xdg-utils/xdg-screensaver b/comp/src/gb.desktop/xdg-utils/xdg-screensaver
--- a/comp/src/gb.desktop/xdg-utils/xdg-screensaver
+++ b/comp/src/gb.desktop/xdg-utils/xdg-screensaver
@@ -202,7 +202,6 @@ binary_to_desktop_file()
 
 #-------------------------------------------------------------
 # map a .desktop file to a binary
-## FIXME: handle vendor dir case
 desktop_file_to_binary()
 {
     search="${XDG_DATA_HOME:-$HOME/.local/share}:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
@@ -210,14 +209,33 @@ desktop_file_to_binary()
     IFS=:
     for dir in $search; do
         unset IFS
-        [ "$dir" ] && [ -d "$dir/applications" ] || continue
-        file="$dir/applications/$desktop"
-        [ -r "$file" ] || continue
-        # Remove any arguments (%F, %f, %U, %u, etc.).
-        command="`grep -E "^Exec(\[[^]=]*])?=" "$file" | cut -d= -f 2- | first_word`"
-        command="`which "$command"`"
-        readlink -f "$command"
-        return
+        [ "$dir" ] && [ -d "$dir/applications" ] || [ -d "$dir/applnk" ] || continue
+        # Check if desktop file contains -
+        if [ "${desktop#*-}" != "$desktop" ]; then
+            vendor=${desktop%-*}
+            app=${desktop#*-}
+            if [ -r $dir/applications/$vendor/$app ]; then
+                file_path=$dir/applications/$vendor/$app
+            elif [ -r $dir/applnk/$vendor/$app ]; then
+                file_path=$dir/applnk/$vendor/$app
+            fi
+        fi
+        if test -z "$file_path" ; then
+            for indir in "$dir"/applications/ "$dir"/applications/*/ "$dir"/applnk/ "$dir"/applnk/*/; do
+                file="$indir/$desktop"
+                if [ -r "$file" ]; then
+                    file_path=$file
+                    break
+                fi
+            done
+        fi
+        if [ -r "$file_path" ]; then
+            # Remove any arguments (%F, %f, %U, %u, etc.).
+            command="`grep -E "^Exec(\[[^]=]*])?=" "$file_path" | cut -d= -f 2- | first_word`"
+            command="`which "$command"`"
+            readlink -f "$command"
+            return
+        fi
     done
 }
 
@@ -379,7 +397,7 @@ check_common_commands()
             ;;
 
             --version)
-            echo "xdg-screensaver 1.1.0 rc3"
+            echo "xdg-screensaver 1.1.3"
             exit_success
             ;;
         esac
@@ -422,8 +440,15 @@ detectDE()
          KDE)
            DE=kde;
            ;;
+         # Deepin Desktop Environments
+         DEEPIN|Deepin|deepin)
+           DE=dde;
+           ;;
          LXDE)
            DE=lxde;
+           ;;
+         LXQt)
+           DE=lxqt;
            ;;
          MATE)
            DE=mate;
@@ -446,6 +471,7 @@ detectDE()
       elif xprop -root _DT_SAVE_MODE 2> /dev/null | grep ' = \"xfce4\"$' >/dev/null 2>&1; then DE=xfce;
       elif xprop -root 2> /dev/null | grep -i '^xfce_desktop_window' >/dev/null 2>&1; then DE=xfce
       elif echo $DESKTOP | grep -q '^Enlightenment'; then DE=enlightenment;
+      elif [ x"$LXQT_SESSION_CONFIG" != x"" ]; then DE=lxqt;
       fi
     fi
 
@@ -484,6 +510,10 @@ detectDE()
       # but not in GNOME 3.x
       which gnome-default-applications-properties > /dev/null 2>&1  || DE="gnome3"
     fi
+
+    if [ -f "$XDG_RUNTIME_DIR/flatpak-info" ]; then
+      DE="flatpak"
+    fi
 }
 
 #----------------------------------------------------------------------------
@@ -501,6 +531,18 @@ kfmclient_fix_exit_code()
     test "$minor" -gt 5 && return $1
     test "$release" -gt 4 && return $1
     return 0
+}
+
+#----------------------------------------------------------------------------
+# Returns true if there is a graphical display attached.
+
+has_display()
+{
+    if [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ]; then
+        return 0
+    else
+        return 1
+    fi
 }
 
 # Check if we can use "mv -T"
@@ -577,6 +619,10 @@ perform_action()
 
     mate_screensaver)
       screensaver_mate_screensaver "$1"
+      ;;
+
+    cinnamon)
+      screensaver_cinnamon_screensaver "$1"
       ;;
 
     xscreensaver)
@@ -849,16 +895,29 @@ screensaver_kde3()
     esac
 }
 
+xset_screensaver_timeout()
+{
+  xset q | sed '/^Screen Saver:/,/^[^ ]/ { s/.*timeout: *\([0-9]*\).*/\1/; t }; d'
+}
+
 screensaver_xserver()
 {
     case "$1" in
         suspend)
-        xset s off > /dev/null
+        timeout=`xset_screensaver_timeout`
+        if [ "$timeout" -gt 0 ]; then
+            echo "$timeout" > "$screensaver_file.xset"
+            xset s off > /dev/null
+        fi
         result=$?
         ;;
 
         resume)
-        xset s default > /dev/null
+        if [ -f "$screensaver_file.xset" ] ; then
+            value=`cat "$screensaver_file.xset"`
+            xset s $value > /dev/null
+            rm -f "$screensaver_file.xset"
+        fi
         result=$?
         ;;
 
@@ -873,7 +932,7 @@ screensaver_xserver()
         ;;
 
         status)
-        timeout=`xset q | sed '/^Screen Saver:/,/^[^ ]/ { s/.*timeout: *\([0-9]*\).*/\1/; t }; d'`
+        timeout=`xset_screensaver_timeout`
         result=$?
         if [ "$timeout" -gt 0 ]; then
             echo "enabled"
@@ -1043,7 +1102,7 @@ screensaver_mate_screensaver()
 {
 # DBUS interface for mate-screensaver
 # This is same as gnome's for now but may change in the future as MATE
-# does not follow gnome's developement necessarily.
+# does not follow gnome's development necessarily.
     case "$1" in
         suspend)
         screensaver_suspend_loop \
@@ -1105,6 +1164,88 @@ screensaver_mate_screensaver()
             return 1
         else
             echo "disabled"
+        fi
+        ;;
+
+        *)
+        echo "ERROR: Unknown command '$1" >&2
+        return 1
+        ;;
+    esac
+}
+
+screensaver_cinnamon_screensaver()
+{
+# DBUS interface for cinnamon-screensaver
+# https://raw.githubusercontent.com/linuxmint/cinnamon-screensaver/master/doc/dbus-interface.html
+    case "$1" in
+        suspend)
+        screensaver_suspend_loop \
+        dbus-send --session \
+                  --dest=org.cinnamon.ScreenSaver \
+                  --type=method_call \
+                  /org/cinnamon/ScreenSaver \
+                  org.cinnamon.ScreenSaver.SimulateUserActivity \
+                  2> /dev/null
+        result=$?
+        ;;
+
+        resume)
+        # Automatic resume when $screensaver_file disappears
+        result=0
+        ;;
+
+        activate)
+        dbus-send --session \
+                  --dest=org.cinnamon.ScreenSaver \
+                  --type=method_call \
+                  /org/cinnamon/ScreenSaver \
+                  org.cinnamon.ScreenSaver.SetActive \
+                  boolean:true \
+                  2> /dev/null
+        result=$?
+        ;;
+
+        lock)
+        dbus-send --session \
+                  --dest=org.cinnamon.ScreenSaver \
+                  --type=method_call \
+                  /org/cinnamon/ScreenSaver \
+                  org.cinnamon.ScreenSaver.Lock \
+                  string:"" \
+                  2> /dev/null
+
+        result=$?
+        ;;
+
+        reset)
+        # Turns the screensaver off right now
+        dbus-send --session \
+                  --dest=org.cinnamon.ScreenSaver \
+                  --type=method_call \
+                  /org/cinnamon/ScreenSaver \
+                  org.cinnamon.ScreenSaver.SimulateUserActivity \
+                 2> /dev/null
+        result=$?
+        ;;
+
+        status)
+        status=`dbus-send --session \
+                          --dest=org.cinnamon.ScreenSaver \
+                          --type=method_call \
+                          --print-reply \
+                          --reply-timeout=2000 \
+                          /org/cinnamon/ScreenSaver \
+                          org.cinnamon.ScreenSaver.GetActive \
+                          | grep boolean | cut -d ' ' -f 5`
+        result=$?
+        if [ x"$status" = "xtrue" ]; then
+            echo "enabled"
+        elif [ x"$status" = "xfalse" ]; then
+            echo "disabled"
+        else
+            echo "ERROR: dbus org.cinnamon.ScreenSaver.GetActive returned '$status'" >&2
+            return 1
         fi
         ;;
 
