[CONFIGURATION] * NEW: Print a resume after "make install".
git-svn-id: svn://localhost/gambas/trunk@3238 867c0c6c-44f3-4631-809d-bfa615b0a4ec

diff --git a/app/Makefile.am b/app/Makefile.am
--- a/app/Makefile.am
+++ b/app/Makefile.am
@@ -5,10 +5,15 @@ install-exec-local:
 	@(cd $(srcdir)/src; d=`pwd`; \
 	  for p in `cat INSTALL`; do \
 	    echo "Compiling $$p..."; cd $$d/$$p; \
-	    $(DESTDIR)$(bindir)/gbc$(GAMBAS_VERSION) -ag -r $(DESTDIR)$(prefix) && \
-	      $(DESTDIR)$(bindir)/gba$(GAMBAS_VERSION) && \
-	      rm -rf .gambas && \
-	      $(INSTALL) $$p.gambas $(DESTDIR)$(bindir) || echo "|| Unable to compile $$p" >> $(top_srcdir)/warnings.log; \
+	    $(DESTDIR)$(bindir)/gbc$(GAMBAS_VERSION) -ag -r $(DESTDIR)$(prefix); \
+	    if test $$? -eq 0; then \
+	      $(DESTDIR)$(bindir)/gba$(GAMBAS_VERSION); \
+	      rm -rf .gambas; \
+	      echo "Installing $$p..."; \
+	      $(INSTALL) $$p.gambas $(DESTDIR)$(bindir); \
+	    else \
+	      echo "|| Unable to compile $$p" >> ../../../warnings.log; \
+	    fi \
 	  done)
 	##@if test "$(bindir)" != "$(ROOT)/usr/bin" && test "$(bindir)" != "$(ROOT)/usr/bin/"; then
 	@ln -s gambas$(GAMBAS_VERSION).gambas $(DESTDIR)$(bindir)/gambas$(GAMBAS_VERSION) || true
diff --git a/comp/Makefile.am b/comp/Makefile.am
--- a/comp/Makefile.am
+++ b/comp/Makefile.am
@@ -25,20 +25,24 @@ install-exec-local:
 	  echo "Compiling $$p..."; \
 	  cd $$d/$$p; \
 	  $(DESTDIR)$(bindir)/gbc$(GAMBAS_VERSION) -ag -r $(DESTDIR)$(prefix); \
-	  $(DESTDIR)$(bindir)/gba$(GAMBAS_VERSION); \
-	  rm -rf .gambas; \
-	  echo "Installing $$p..."; \
-	  $(INSTALL) $$p.gambas $(DESTDIR)$(gblibdir); \
-	  $(INSTALL) .component $(DESTDIR)$(gblibdir)/$$p.component; \
-	  chmod a-x $(DESTDIR)$(gblibdir)/$$p.component; \
-	  $(INSTALL) .info $(DESTDIR)$(gbdatadir)/info/$$p.info; \
-	  chmod a-x $(DESTDIR)$(gbdatadir)/info/$$p.info; \
-	  $(INSTALL) .list $(DESTDIR)$(gbdatadir)/info/$$p.list; \
-	  chmod a-x $(DESTDIR)$(gbdatadir)/info/$$p.list; \
-	  if test -d .hidden/control; then \
-	    $(INSTALL) -d $(DESTDIR)$(gbdatadir)/control; \
-	    $(INSTALL) -d $(DESTDIR)$(gbdatadir)/control/$$p; \
-	    $(INSTALL) .hidden/control/*.png $(DESTDIR)$(gbdatadir)/control/$$p; \
+	  if test $$? -eq 0; then \
+	    $(DESTDIR)$(bindir)/gba$(GAMBAS_VERSION); \
+	    rm -rf .gambas; \
+	    echo "Installing $$p..."; \
+	    $(INSTALL) $$p.gambas $(DESTDIR)$(gblibdir); \
+	    $(INSTALL) .component $(DESTDIR)$(gblibdir)/$$p.component; \
+	    chmod a-x $(DESTDIR)$(gblibdir)/$$p.component; \
+	    $(INSTALL) .info $(DESTDIR)$(gbdatadir)/info/$$p.info; \
+	    chmod a-x $(DESTDIR)$(gbdatadir)/info/$$p.info; \
+	    $(INSTALL) .list $(DESTDIR)$(gbdatadir)/info/$$p.list; \
+	    chmod a-x $(DESTDIR)$(gbdatadir)/info/$$p.list; \
+	    if test -d .hidden/control; then \
+	      $(INSTALL) -d $(DESTDIR)$(gbdatadir)/control; \
+	      $(INSTALL) -d $(DESTDIR)$(gbdatadir)/control/$$p; \
+	      $(INSTALL) .hidden/control/*.png $(DESTDIR)$(gbdatadir)/control/$$p; \
+	    fi \
+	  else \
+	    echo "|| Unable to compile $$p" >> ../../../warnings.log; \
 	  fi \
 	  done; true)
 
